### ISSUE TITLE
Get-OSBuild function is broken. 20H2 is interpreted as a function

### ISSUE THREAD

**Issue by HermanGB** [MSEndpointMgr/ModernDriverManagement#101]
Line 965: $OSVersion = 20H2

![image](https://user-images.githubusercontent.com/23094138/117632865-c7708300-b17d-11eb-9567-1900dde89729.png)

Added single quotation mark around '20H2' and script is again working. 

![image](https://user-images.githubusercontent.com/23094138/117633958-cd1a9880-b17e-11eb-8463-07cf8b39b4d2.png)

ApplyDriverPackage.log did not log this error. Had to add some additional error handling.
Write-CMLogEntry -Value "[ApplyDriverPackage]: Dumping last error $Error[0].Exception.Message" -Severity 3

![image](https://user-images.githubusercontent.com/23094138/117633626-8462df80-b17e-11eb-95ff-cd62f35d7e12.png)

Unfortunately I did not write down the error message that was thrown by **$Error[0].Exception.Message**.
This can be recreated by running **-DriverUpdate -Endpoint "SiteServer"** on 20H2 client.

**Comment by heinzmum** [comment]
I just ran into the same problem,
thanks for figuring out this!

**Comment by HermanGB** [comment]
Fixed in 4.1.2
