### ISSUE TITLE
TS v4 Script gets 404 error

### ISSUE THREAD

**Issue by kquinn64** [MSEndpointMgr/ModernDriverManagement#112]
Have a new install and the v4 script is erroring whenever we run it in a TS, so we are running it in the ISE in debug mode. I have verified the correct driver package is downloaded and distributed. If I just run the PS to get to the admin service it runs fine... if I change the MDMAcct pwd I get a 401 error (bad password)
[ApplyDriverPackage.log](https://github.com/MSEndpointMgr/ModernDriverManagement/files/6865252/ApplyDriverPackage.log)

**Comment by HermanGB** [comment]
Add this to the script and see if this allows you to figure out what is wrong. 
**_Write-CMLogEntry -Value "[ApplyDriverPackage]: Dumping last error $Error[0].Exception.Message" -Severity 3_**

Should be added inside the catch [System.Exception] at line 2265. 
![image](https://user-images.githubusercontent.com/23094138/128156391-b8c01706-088a-4c83-8e96-9d2b26d436b8.png)

**Comment by kquinn64** [comment]
Found the issue, thank you for the input

Turns out the user(service acct) had accidently been removed from any rights in the console by someone who didn't understand why a 'service acct' needed console rights :)
