### ISSUE TITLE
How to use the DebugMode

### ISSUE THREAD

**Issue by 20H221H1** [MSEndpointMgr/ModernDriverManagement#115]
Hi, I am new user of DAT and have some questions that I hope some one will guide me through.

When I run the command ".......\Invoke-CMApplyDriverPackage.ps1 -DebugMode -Endpoint "sccm-SITE.domain.local" -UserName "UserName" -Password "******" -TargetOSVersion 20H2"

There is no answer on the screen.
1) Am I doing something wrong or should I look in a log file somewhere?
2) Most I use the DAT servrice account (SVC_CM_AS) credentials ?

I guess the debugmode should return whether the driver exist in ConfigMgr or not ?
As I understand the script, it should in debugmode create a log file "C:\Temp\ApplyDriverPackage.log" which I cannot find.

Any help will be appreciated

**Comment by HermanGB** [comment]
1. The log file can be found in C:\Windows\Temp\ApplyDriverPackage.log
2. You can use any user account that has read access to ConfigMgr
