### ISSUE TITLE
Apply driver package step fails (returns errorcode 1) - Invoke-CMApplyDriverPackage.ps1 v4.0.1

### ISSUE THREAD

**Issue by Noizcontroller** [MSEndpointMgr/ModernDriverManagement#15]
Hi

I'm trying to setup MDM on our MCEM 2002 environment. I was able to download and create the driver packages with the Driver Automation tool but the part for the task sequence does not work. I'm using version 4.0.1 of the Invoke-CMApplyDriverPackage.ps1 script. I was able to setup the AdminService on our MCEM and it is working correctly. I was also able to configure a read-only user and I added the credentials in the task sequence.

![image](https://user-images.githubusercontent.com/30369760/88664822-f382b200-d0dd-11ea-9579-27aabadef0a4.png)

When the "Apply driver package" step runs, the script is able to connect to the admin service and filter the correct driver package but then it suddenly stops with exit code 1 and without decent logging what went wrong. Any suggestions what could be wrong? The package with the drivers is distributed to the DP.

![20200728_142802](https://user-images.githubusercontent.com/30369760/88665363-cb478300-d0de-11ea-9754-9d355dede975.jpg)

Kind regards
Niels

**Comment by wiesel24** [comment]
Same Problem! I've tried it Multiple Times but no success

**Comment by ABitBA** [comment]
Same Problem here - Error 1

**Comment by NickolajA** [comment]
Have you seen our new docs on how to use v4 of the script?

https://msendpointmgr.com/modern-driver-management/

**Comment by Noizcontroller** [comment]
It's now working with the latest version (4.0.2) of the script. Thx!
