### ISSUE TITLE
TargetOSVersion question

### ISSUE THREAD

**Issue by Snofly** [MSEndpointMgr/ModernDriverManagement#153]
Hello,

I have some PCs that have 20H2 driver package available via the MDM tool, but there is not a 21H2 driver pack available. 

It appears the MDM tool can apply the 20H2 driver package successfully to a 21H2 WIM by using this:

-BareMetal -Endpoint "MYSERVER" -TargetOSVersion "20H2" -TargetOSName 'Windows 10'

In my task sequence I am using a 21H2 WIM file, but as you can see above I set MDM to use a different target OS version. The log file shows the MDM tool ran successfully with no errors and did apply the 20H2 package. The drivers are installed on the PC properly.

Is there any issue with telling the script to use a targetOSversion that differs from my WIM file? (21H2 WIM)

Note: using  -TargetOSVersion "21H2" results in the script failing and not applying drivers. With error: Validation failed with empty list of matched driver packages, script execution will be terminated

Thank you!

**Comment by sveken** [comment]
This is where you would use -OSVersionFallback
OSVersionFallback Use this switch to check for drivers packages that matches earlier versions of Windows than what's specified as input for TargetOSVersion.

This way you can have your target as 21H2, and if there are 21H2 drivers they will be installed, but if no results are found it will fall back to your 20H2 drivers. 

Apart from that, normally no, you will not have an issue
