### ISSUE TITLE
Dynamically apply drivers continuously fails

### ISSUE THREAD

**Issue by mherbert18** [MSEndpointMgr/ModernDriverManagement#170]
I recently updated DAT to be version 7.0.4 and I had imported several Dell Windows 10 drivers as well as Windows 11 drivers. When using the Invoke-CMApplyDriverPackage.ps1 in a dynamically apply drivers task sequence step, the step is failing now for every model I try to deploy using -BareMetal deployment options. I updated the script to be the latest version, 4.2.0 from 4.1.3, and used the new parameters to differentiate between Windows 10 and Windows 11 and it didn't work. I then reverted back to the 4.1.3 version and got rid of the additional parameters and any duplicate Win 11 driver packages for a specific model and I am still not able to get the dynamically apply drivers step to work. I've tried downloading and manually importing driver packages into SCCM directly from Dell, deleting and recreating script packages, deleting and retrying to import driver packages via DAT...nothing is working. It was working perfectly fine before I updated DAT and imported new drivers. I also cannot find any logs or get the script to run in debug mode. It also appears that DAT version 7.0.4 is setting driver versions to 5420 for the A08 and A12 driver packs for the Latitude 5420 when importing into SCCM, I have tried to change this manually to the correct driver version but that doesn't seem to change any outcomes. Regardless of the changes I make, I continually get error code 0x00000001.

**Comment by YouLoopedIt** [comment]
Hey there, I am getting the same error code when TS is at Dynamically Apply Drivers step. How did you get this working?

Thanks!
-Rob

**Comment by mherbert18** [comment]
Hi Rob,

I don't remember exactly what I did to resolve this issue. I do remember that for the CABs that were having issues didn't have content in them. I think I set DAT to save the source files and then I went into the downloads folder and extracted the files myself and manually copied them into the driver package folder for the driver giving me issues. Then I started the automation tool to package those properly and import them into SCCM and since they were already downloaded and extracted, it just packaged it and imported. From there, I think I might have also had to change the version number in SCCM to match the reported driver version (A12, etc) instead of the model. Or you could try changing the source folder before you try to import into SCCM.

**Comment by YouLoopedIt** [comment]
Thanks so much for getting back to me! No matter what I do, I'm still coming up with this stupid error haha. SMSTS.log doesn't provide any errors either and it seems like applydriverpackage.log isn't even being created. I didn't even change anything and it just started doing this out of nowhere.

I appreciate you taking the time to get back to me, I will respond back when/if I figure this out.

-Rob
