### ISSUE TITLE
AdminService 404 errors

### ISSUE THREAD

**Issue by TheSnootch** [MSEndpointMgr/ModernDriverManagement#179]
I'm suddenly getting 404 errors in the AdminService logs when the script queries for BIOS or driver packages.  The account password hasn't expired so I don't know why it just stopped working.

Any ideas where to start checking?  What permissions are required for the account being used?  It currently has the "Read-Only Analyst" role in SCCM which I thought was all it needed.

Could this be an IIS permissions issue?

If I paste the following query into a browser logged on as myself, I get a list of packages.

https://<server.name>/AdminService/wmi/SMS_Package?$filter=contains(Name,'Drivers')

If I open an incognito window and paste they query into the browser then use the credentials I've been using for several years I get:

{"error":{"code":"404","message":"Access denied  WMI QUERY: "}}

**Comment by TheSnootch** [comment]
Found it.  The SCCMAdmins group didn't have WMI permissions to query per the following link.

https://www.anoopcnair.com/configmgr-sccm-how-to-verify-wmi-permission-for-console-access/

Anoop saves the day yet again.

**Comment by sveken** [comment]
Thanks for this follow up.

Just been upgrading all my SCCM servers from 2016 to 2022 and i have run into this issue on every single one. 
Thanks to your link just adding the account i use for the drivers to the WMI has resolved the issue.
