### ISSUE TITLE
-DriverUpdate and -TargetOSVersion do not work together

### ISSUE THREAD

**Issue by shwarmy** [MSEndpointMgr/ModernDriverManagement#20]
I found the problem and the solution. The problem is caused by the following line not being present in the script. Add this line fixes it.
	[parameter(Mandatory = $true, ParameterSetName = "DriverUpdate")]

Having the section look like this resolves the issue updating drivers from within an existing OS. 

	[parameter(Mandatory = $true, ParameterSetName = "BareMetal", HelpMessage = "Define the value that will be used as the target operating system version e.g. '2004'.")]
	[parameter(Mandatory = $true, ParameterSetName = "DriverUpdate")]
	[parameter(Mandatory = $true, ParameterSetName = "OSUpgrade")]
	[parameter(Mandatory = $true, ParameterSetName = "PreCache")]
	[parameter(Mandatory = $true, ParameterSetName = "Debug")]
	[parameter(Mandatory = $false, ParameterSetName = "XMLPackage")]
	[ValidateNotNullOrEmpty()]
	[ValidateSet("2004", "1909", "1903", "1809", "1803", "1709", "1703", "1607")]
	[string]$TargetOSVersion,

Was this intended?

**Comment by NickolajA** [comment]
Yes, that scenario is pulling the required OS data directly from the machine the script is running on, hence no need to pass the data in as parameter input.

**Comment by shwarmy** [comment]
Just to make sure that I understand this correctly that it is intended to NOT be able to use the -TargetOSVersion with the -DriverUpdate parameter?
