### ISSUE TITLE
PowerShell Error.  You cannot call a method on a null-valued expression. At line:17154 char:5

### ISSUE THREAD

**Issue by Get-SomeCofee** [MSEndpointMgr/ModernDriverManagement#220]
Trying to get started using the tool. I'm getting this error when running DriverAutomationTool.exe  Any idea how I can get past this?  I could not find the PS1 file to look at the PowerShell code to troubleshoot this further. Also Microsoft is checked and grayed out and can't be unchecked.

```
[Start Up]
- Initialising Driver Automation Tool
- Loading required PowerShell modules
- Checking for preinstalled PS modules
- Importing module BitsTransfer
[Launching GUI]
[Azure Registy Settings Detected]
- Obtaining all Azure values from registry path HKLM:\SOFTWARE\MSEndpointMgr\DriverAutomationTool
- Setting values in the UI
You cannot call a method on a null-valued expression.
At line:17154 char:5
+ ...             $OSBuild = ($WindowsBuildHashTable.Item("$OSBuild")).Spli ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
 

![image](https://user-images.githubusercontent.com/99751000/210659667-42be72b2-76e0-434d-b749-e8832aedd2d3.png)

**Comment by SnapZinger** [comment]
Hey, we recently ran into this same issue. Currently fallen back to our old method of driver deployment.... I have not been able to resolve this issue yet.

**Comment by slundy** [comment]
Same issue, but it's a new install.  My other install (same version) works but just downloads drivers and then hangs.
