### ISSUE TITLE
Unable to find the driver in driver automation tool 

### ISSUE THREAD

**Issue by imran9k** [MSEndpointMgr/ModernDriverManagement#248]
Unable to find the driver. Post search HP Z2 Mini G9 Workstation And HP ZBook 14u G5

what we need to do when don't find post search. these are new model devices.

please suggest

![image](https://github.com/MSEndpointMgr/ModernDriverManagement/assets/53402189/d390fb96-066c-4043-b611-f3ceb9074fee)

**Comment by MarkReynolds6** [comment]
It is listed as Z2 G9 Mini rather than Z2 Mini G9, for the 14u G5 there are no Windows 11 driver packs.

If in doubt check the HP site as that where the tool gets all it's driver packs from:
**https://hpia.hpcloud.hp.com/downloads/driverpackcatalog/HP_Driverpack_Matrix_x64.html**

**Comment by imran9k** [comment]
Thanks for the suggestion, I am able to find the driver.
