### ISSUE TITLE
Cannot get this to work. 

### ISSUE THREAD

**Issue by beaswax19816** [MSEndpointMgr/ModernDriverManagement#254]
Have everything setup but continue to get a task sequence error in windows pe. . Fails with a  value of 1. 

-BareMetal -Endpoint "SCCMCB.archildrens.org" -TargetOSName "Windows 10" -TargetOSVersion "22H2"  -OSVersionFallback
or
-BareMetal -Endpoint 'SCCMCB.archildrens.org' -TargetOSName 'Windows 10' -TargetOSVersion '22H2'  -OSVersionFallback

I've tried both single and double quotes and it still doesnt work. I have the driver packages setup in SCCM and have created the account but I cannot get past it failing everytime. 

Powershell modules have been added to the boot image. I am also using the latest version of the script.

**Comment by yogiwan** [comment]
look in your AppyDriverPackage.log what specific error occurs.
I had a similar issue with the problem beeing the script not able to match "Windows 10".

If this is the same error, I fixed this by setting double quotes in the command-line:
-BareMetal -Endpoint 'SCCMCB.archildrens.org' -TargetOSName "'Windows 10'" -TargetOSVersion '22H2' -OSVersionFallback

maybe this helps

**Comment by beaswax19816** [comment]
Thank you! Those pesky quotes always get me.
