### ISSUE TITLE
Unable to find driver for Lenovo ThinkPad P14S Gen 2 Type 21A0 21A1

### ISSUE THREAD

**Issue by nateg1216** [MSEndpointMgr/ModernDriverManagement#270]
Greetings,

Lenovo hadn't properly updated their driver packages to show that it supported 22H2. I submitted a case with Lenovo to update this and it now shows correctly in DAT, but I get an error when I try to download, extract, and import: "[Error] - Unable to find driver for Lenovo ThinkPad P14S Gen 2 Type 21A0 21A1"

I can download the file directly from Lenovo, perhaps DAT cannot? Can you investigate?
![DAT Error](https://github.com/MSEndpointMgr/ModernDriverManagement/assets/143038825/1d3987d5-a228-4990-a4ed-14b55d8860f6)

**Comment by ajn142attamu** [comment]
Is this helpful?
https://github.com/MSEndpointMgr/ModernDriverManagement/issues/274#issuecomment-1979629547

**Comment by nateg1216** [comment]
> Is this helpful? [#274 (comment)](https://github.com/MSEndpointMgr/ModernDriverManagement/issues/274#issuecomment-1979629547)

Thanks for this. I didn't see 7.2.3 came out. I updated to that version and all worked well. I appreciate your reply!
