### ISSUE TITLE
Suddenlty Task sequnce is failing with this error code - 0x00000001 and Error 1

### ISSUE THREAD

**Issue by shindesganesh** [MSEndpointMgr/ModernDriverManagement#281]
We are on the latest version of tool  and using Windows 11 23H2

![image](https://github.com/MSEndpointMgr/ModernDriverManagement/assets/91619872/c70e22b2-4ba3-4cdc-bf15-c29e700ef738)

**Comment by bacasillas1** [comment]
What was the fix for this? I'm new to MDM and currently running into this issue.
