### ISSUE TITLE
Retrieved a total of '0' driver packages

### ISSUE THREAD

**Issue by MEConfigMgr** [MSEndpointMgr/ModernDriverManagement#35]
I am receiving the following error message when running a DebugMode or BareMetal. Https is enabled in my environment (binding IIS Cert for https is exist) and AdminService appears to be working fine:
![image](https://user-images.githubusercontent.com/61551639/93718347-288d0d00-fb41-11ea-80bb-f0306f5fe1eb.png)

**Comment by MEConfigMgr** [comment]
I forgot to mention that when I run the script in debugmode I am unable to see any activities in the AdminService.log. However, the log shows "response code [200] reason [OK]" when I visit https://myFQDNCM/adminservice/v1.0/$metadata

**Comment by Staja** [comment]
Did you check what version of the script you have? Looks like https://github.com/maurice-daly/DriverAutomationTool/issues/124

**Comment by maurice-daly** [comment]
Please confirm that the account you are using to query the admin service or web service has at least read-only analyst rights to configuration manager. If this is not the case, this is the expected behavior.

**Comment by MarcusNISD** [comment]
I'm also having this issue and the account im using does have "read-only analyst" rights.
