### ISSUE TITLE
7zip doesn't work

### ISSUE THREAD

**Issue by nodiaque** [MSEndpointMgr/ModernDriverManagement#36]
Hello,

Using Driver automation Tool 6.4.9 and version 4.0.5 of the script, 7zip archive doesn'T work properly. When I create the package in either uncompress or zip, the computer install fine and no issue. If I use 7zip compression, it then does error during the dism and once booted, a lot of driver missing. I tried with various computer and all consistent result.

For my current exemple, I have uncompress driver of 3.3gig, zip of 2gig and 7z of 1.3gig. When unzipping, all of them are 3.3gig thus I'm unsure where's the problem, either the .exe of 7zip not unzipping properly or at the right place? The script does say a dism error occured:

` - An error occurred while installing drivers. Continuing with warning code: 2. See DISM.log for more details`
[dism.log](https://github.com/MSEndpointMgr/ModernDriverManagement/files/5256663/dism.log)

**Comment by dannz87** [comment]
Do you see in the logs that the Driver package has been extracted? Is your 7zip exe named DriverPackage.exe?

**Comment by nodiaque** [comment]
Hello,

The driver are extracted, the file exist and is properly named, but drivers doesn't work and once in the OS, lot's of missing drivers.

I unzip manually and the file size and count was the same as the unzip one. But the size is very different. Tried on various model and make, and always same result.

THanks

**Comment by meterien** [comment]
I have an similar issue when i upgrade to 4.0.6. In my case, to debug i had a write-CMLog entry to pop the 7zip error message and it said : WARNING: This command cannot be run due to the error: This version of %1 is not compatible with the version of Windows 

My boot image is x64

**Comment by meterien** [comment]
My wrong i didn't read the documentation carefully when i created my 7zip package. I did'nt copy the  7z.sfx
I will repackage all my driver and test...

**Note**
For 7-Zip support, you will need to install 7-Zip on the server where you are packaging the drivers, and
replace the 7z.sfx file with the one packaged with the Driver Automation Tool. This file was re-compiled,
so it supports 64 bit installation in WinPe.

**Comment by TokenRing** [comment]
Hi @meterien - I think I'm running into the same issue as you. In my WinPE environment, my DriverPackage.exe files are successfully copied over to the test computer, but extraction doesn't work. Trying to run .\DriverPackage.exe directly in WinPE says "Program DriverPackage.exe failed to run: the specified executable is not a valid application for this OS platform." - like you, I'm also on x64 boot image.

Can you let me know which documentation you are referring to? I followed the "4 step" instructions listed here - https://msendpointmgr.com/modern-driver-management/#implementation-instructions - and I don't see anything about that Note you included about 64 bit WinPE installation, so I'm worried there were instructions I should have followed that I didn't even see!

I do have "C:\Program Files\MSEndpointMgr\Driver Automation Tool\7Zip\7z.sfx" on my packaging computer, and I'm sure I can use it to replace an existing sfx in 7-zip on the comp, but I'm going to feel silly if there was instructions telling me to do that on the website and I missed them somehow.

Furthermore, regarding logging (or lack thereof)

My Apply-Driver-Package.log file on my test computer shows this:
```
2020-11-30 1:48:41 PM	[DriverPackageInstall]: Starting driver package install phase
2020-11-30 1:48:41 PM	 - Downloaded driver package content contains a compressed archive with driver content
2020-11-30 1:48:41 PM	 - Attempting to decompress 7-Zip driver package content file: DriverPackage.exe
2020-11-30 1:48:41 PM	 - Decompression destination: C:\_SMSTaskSequence\DriverPackage\SSC00379
2020-11-30 1:48:43 PM	 - Attempting to apply drivers using dism.exe located in: C:\_SMSTaskSequence\DriverPackage\SSC00379
```

But according to lines 1942-1958 of the [ps1 file](https://github.com/MSEndpointMgr/ModernDriverManagement/blob/master/Invoke-CMApplyDriverPackage.ps1):
```
				"*.exe" {
					Write-CMLogEntry -Value " - Attempting to decompress 7-Zip driver package content file: $($DriverPackageCompressedFile.Name)" -Severity 1
					Write-CMLogEntry -Value " - Decompression destination: $($ContentLocation)" -Severity 1
					$ReturnCode = Invoke-Executable -FilePath $DriverPackageCompressedFile.FullName -Arguments "-o`"$($ContentLocation)`" -y"
					
					# Validate 7-Zip driver extraction
					if ($ReturnCode -eq 0) {
						Write-CMLogEntry -Value " - Successfully decompressed 7-Zip driver package content file" -Severity 1
					}
					else {
						Write-CMLogEntry -Value " - An error occurred while decompressing 7-Zip driver package content file. Return code from self-extracing executable: $($ReturnCode)" -Severity 3

						# Throw terminating error
						$ErrorRecord = New-TerminatingErrorRecord -Message ([string]::Empty)
						$PSCmdlet.ThrowTerminatingError($ErrorRecord)
					}
				}
```

shouldn't my resulting log file show me either that a successful decompression occurred, or one didn't occur? The if/else statements leave no other option, right? Seems like logging might not be working?

**Comment by meterien** [comment]
Hi @TokenRing I had the same issue you describe so the tool do not check if the unzipping error. 

When you download the tool it has a documentation in pdf format. Here a link directly from github : [Doc](https://github.com/maurice-daly/DriverAutomationTool/blob/master/Content/DriverAutomationTool-UserGuide.pdf)

In section 6.8 there is a note section with the instruction to copy the file.

**Comment by TokenRing** [comment]
Thanks meterien. That seemed to work for me too. WinPE can now open and run the 7zip .exe files after I remade them all using the included .sfx file. 

@NickolajA and @maurice-daly - perhaps your website should be updated to mention that users should read the Documentation PDF in full before attempting an install? Right now, going off the main page at https://msendpointmgr.com/modern-driver-management/ no PDF is mentioned, and I followed the 4 step guide fully and never would have known that I needed to replace 7-zip's included sfx with a different one from yours.

Anyway, just a thought on making things clearer for your happy users - and I'm quite happy with this tool! Hopefully this would lead to less tickets sent your way on github.

**Comment by spitfire** [comment]
> Thanks meterien. That seemed to work for me too. WinPE can now open and run the 7zip .exe files after I remade them all using the included .sfx file.
> 
> [@NickolajA](https://github.com/NickolajA) and [@maurice-daly](https://github.com/maurice-daly) - perhaps your website should be updated to mention that users should read the Documentation PDF in full before attempting an install? Right now, going off the main page at https://msendpointmgr.com/modern-driver-management/ no PDF is mentioned, and I followed the 4 step guide fully and never would have known that I needed to replace 7-zip's included sfx with a different one from yours.
> 
> Anyway, just a thought on making things clearer for your happy users - and I'm quite happy with this tool! Hopefully this would lead to less tickets sent your way on github.

I just had this happen, 5 years later. THe document mentioning it is not linked anywhere on the site, the guide does not mention it. @maurice-daly it would really help some people to mention that.
