### ISSUE TITLE
Merge repos

### ISSUE THREAD

**Issue by dsolodow** [MSEndpointMgr/ModernDriverManagement#6]
Looks like this repo and https://github.com/MSEndpointMgr/ConfigMgr/tree/master/Operating%20System%20Deployment/Drivers should be one and the same.
Slightly disconcerting that they have different content. :)

**Comment by NickolajA** [comment]
You're absolutely correct. Once the docs page on our web site have been updated the other repo-reference will be removed. The main script in this repo is what contains the latest developments and enhancements, but it also includes a "legacy" version that's version 3.x, but won't be updated going forward as it utilizes the ConfigMgr WebService.
