### ISSUE TITLE
-DriverUpdate fails after retrieving number of driver packages with no real error.

### ISSUE THREAD

**Issue by dtrain187** [MSEndpointMgr/ModernDriverManagement#77]
[ApplyDriverPackage]: Apply Driver Package process initiated	ApplyDriverPackage	2/18/2021 1:33:38 PM	5020 (0x139C)
 - Apply driver package deployment type: DriverUpdate	ApplyDriverPackage	2/18/2021 1:33:38 PM	5020 (0x139C)
 - Apply driver package operational mode: Production	ApplyDriverPackage	2/18/2021 1:33:38 PM	5020 (0x139C)
[PrerequisiteChecker]: Starting environment prerequisite checker	ApplyDriverPackage	2/18/2021 1:33:38 PM	5020 (0x139C)
 - Supported computer platform detected, script execution allowed to continue	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Supported operating system version currently running detected, script execution allowed to continue	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Computer manufacturer determined as: Lenovo	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Computer model determined as: ThinkCentre M720q	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Computer SystemSKU determined as: 10T8	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Computer model detection was successful	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Computer SystemSKU detection was successful	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Computer details successfully verified	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Determined primary computer detection method: SystemSKU	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
[PrerequisiteChecker]: Completed environment prerequisite checker	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
[AdminService]: Starting AdminService endpoint phase	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Attempting to determine AdminService endpoint type based on current active Management Point candidates and from ClientInfo class	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Determined AdminService endpoint type as: Internal	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Successfully read service account user name from TS environment variable 'MDMUserName': S*C*S*C*-*D*I*S*V	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Successfully read service account password from TS environment variable 'MDMPassword': ********	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Setting 'AdminServiceURL' variable to: https://ServerName/AdminService/wmi	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
[AdminService]: Completed AdminService endpoint phase	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
[DriverPackage]: Starting driver package retrieval using method: AdminService	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Querying AdminService for driver package instances	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 - Calling AdminService endpoint with URI: https://Servername/AdminService/wmi/SMS_Package?$filter=contains(Name,'Drivers')	ApplyDriverPackage	2/18/2021 1:33:39 PM	5020 (0x139C)
 _- Retrieved a total of '82' driver packages from AdminService matching operational mode: Production	ApplyDriverPackage	2/18/2021 1:33:40 PM	5020 (0x139C)_
**[ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages	ApplyDriverPackage	2/18/2021 1:33:41 PM	5020 (0x139C)**

**Comment by MichalKir** [comment]
I think I found the issue. Windows build table is referring to 20H2 as an integer instead of a string.
Open up the script in your favourite editor and replace $OSVersion = 20H2 (line 964)  with $OSVersion = "20H2"

**Comment by dtrain187** [comment]
This was the issue with the datatype.
