### ISSUE TITLE
Cannot get it working (Parameter set cannot be resolved using the specified named parameters)

### ISSUE THREAD

**Issue by Wavee7** [MSEndpointMgr/ModernDriverManagement#78]
Hello,

I'm trying to get Driver Automation Tool working since the last days and I'm getting a little bit crazy xD

I did the migration to AdminService and updated the scripts to the latest version. I'm currently running Driver Automation Tool v6.5.2 and Invoke-CMApplyDriverPackage.ps1 v4.1.0.

I'm stuck on the following error and I'm not able to sort it out :

![image](https://user-images.githubusercontent.com/79086831/108519032-8c228e80-72c9-11eb-9fe9-c02da213f12c.png)

Anyone with the same error ?

**Comment by MichalKir** [comment]
Follow the guide. -UserName and -Password are only part of Debug parameter set. You need to set TS-variables MDMUserName and MDMPassword ([https://msendpointmgr.com/modern-driver-management/](https://msendpointmgr.com/modern-driver-management/) step 4)

**Comment by Wavee7** [comment]
Many thanks, I misunderstood that the -Username and -Password was only for the DebugMode.

Many thanks for your help !
