### ISSUE TITLE
OSBuild for DriverUpdate mode needs "

### ISSUE THREAD

**Issue by criiser** [MSEndpointMgr/ModernDriverManagement#91]
https://github.com/MSEndpointMgr/ModernDriverManagement/blob/dc7084bd330201f52c5129cd96464592d4260873/Invoke-CMApplyDriverPackage.ps1#L965

This needs to be wrapped in " - 

RIght now the scripts crashes when being run on 20H2 Build...

/C

**Comment by Staja** [comment]
https://github.com/MSEndpointMgr/ModernDriverManagement/pull/87

**Comment by criiser** [comment]
Agree. This is a duplicate. Closing!!
