### ISSUE TITLE
Combine driver and bios updates

### ISSUE THREAD

**Issue by c-theo** [MSEndpointMgr/ModernDriverManagement#92]
Is it possible to use the new method with AdministrationService to install bios updates instead of using the web service?

Thank you very much.

**Comment by Wavee7** [comment]
You can download the Beta version there :

https://www.github.com/MSEndpointMgr/ConfigMgr/tree/master/Operating%20System%20Deployment%2FBIOS

It works with AdminService and uses the same two variables as for ModernDriverManagement.

I'm using it for Lenovo computers and it works well. You only need one parameter as minimum : -Endpoint
