### ISSUE TITLE
DriverUpdate mode in Invoke-CMApplyDriverPackage.ps1 not working because of bug in Get-OSBuild function.

### ISSUE THREAD

**Issue by mjussen** [MSEndpointMgr/ModernDriverManagement#93]
**Script Invoke-CMApplyDriverPackage.ps1 version 4.1.1.**
Bug: When using the script in 'DriverUpdate' mode the script will crash in the function Get-OSBuild and bail out.
Cause: Line number 965 contains "$OSVersion = 20H2" which is invalid. The value is not a valid integer but a string whereas all other values passed to $OSVersion in the Switch block are integers.

Solution:
All values passed to $OSVersion should be strings enclosed in quotes.
At the least line 965 should say "$OSVersion = '20H2'"

**Comment by SPatrickStevens** [comment]
I can confirm that I had to do this as well. I should have checked on here first, but that was the fix in my case as well!

**Comment by NickolajA** [comment]
Thanks for spotting this mistake, it will be corrected in 4.1.2 that'll be released in the next couple of days.
